# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will runname: Maven Package

on: [push] # github action이 동작할 시점 (push할때 동작)
        
jobs:
  build:
    runs-on: EV                 # 본인 aws서버에서 실행
    permissions:
      contents: read
      packages: write
      
    if: "contains(github.event.head_commit.message, 'deploy')" # 만약 제일 마지막 commit 메세지에 deploy가 포함된다면 배포시작
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8 # OpenJDK 1.8 설치
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Publish with maven # maven활용 war파일 빌드/배포
      env :
        MAVEN_USERNAME : ${{secrets.MAVEN_USERNAME}}
        MAVEN_PASSWORD : ${{secrets.MAVEN_PASSWORD}}
        MAVEN_URL : ${{secrets.MAVEN_URL}}
      run: mvn tomcat7:deploy --file final_EV/pom.xml -Dmvn_project.url=$MAVEN_URL -Dmvn_project.username=$MAVEN_USERNAME -Dmvn_project.password=$MAVEN_PASSWORD
